### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by brainoc** [sn0wmanmj/pydsb#1]
Executing I get the following error:

pi@raspberrypifhem:/mnt/Share $ python3 dsb.py
Traceback (most recent call last):
  File "dsb.py", line 7, in <module>
    print(dsb.get_plans())
  File "/home/pi/.local/lib/python3.5/site-packages/pydsb/__init__.py", line 72, in get_plans
    raw_plans = self.fetch_data()["plans"][0]["Root"]["Childs"]
  File "/home/pi/.local/lib/python3.5/site-packages/pydsb/__init__.py", line 49, in fetch_data
    gzip.decompress(base64.b64decode(json.loads(req.text)["d"]))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by xnacly** [comment]
just do `print(str(dsb.get_plans()))`
That should fix your issue

**Comment by brainoc** [comment]
Thanks for response, I added str but unfortunately no change:
Traceback (most recent call last):
  File "dsb.py", line 7, in <module>
    print(str(dsb.get_plans()))
  File "/home/pi/.local/lib/python3.5/site-packages/pydsb/__init__.py", line 72, in get_plans
    raw_plans = self.fetch_data()["plans"][0]["Root"]["Childs"]
  File "/home/pi/.local/lib/python3.5/site-packages/pydsb/__init__.py", line 49, in fetch_data
    gzip.decompress(base64.b64decode(json.loads(req.text)["d"]))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by BastelPichi** [comment]
This is very likely because the authentication wasnt successful for whatever reason. In patch #2 I've introduced an check for that.

Also please note that naming your file `dsb` could cause problems.
